# Generated by Django 2.2.3 on 2019-07-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
