# Generated by Django 2.2.3 on 2019-07-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_boardpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='slug',
            field=models.SlugField(default='hello-world'),
            preserve_default=False,
        ),
    ]
