# Generated by Django 2.2.3 on 2019-07-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_boardpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardpost',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
