# Generated by Django 2.2.3 on 2019-07-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20190728_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardpost',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
