# Generated by Django 2.2.3 on 2019-08-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20190801_0652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardpost',
            options={'ordering': ['-publish_date', '-updated', '-timestamp']},
        ),
        migrations.AlterField(
            model_name='boardpost',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
