# Generated by Django 2.2.3 on 2019-08-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20190801_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
